/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * sugerido1.java
 *
 * Created on 17/05/2017, 07:05:01 PM
 */

/**
 *
 * @author Fernando
 */
public class sugerido1 extends javax.swing.JFrame {
     String e1, p;
    int n, proximo1,proximo2;
    int proximo3,proximo4, x, y,primoi,primod;
    public sugerido1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        cj1 = new javax.swing.JTextField();
        cj2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.setText("Resultado");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cj1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(cj2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(cj1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(cj2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
    e1 = cj1.getText();
     n = Integer.parseInt(e1);
     int a= 0;
     for (int i = 1; i <= n; i++) {
     a = a + i;
     if (n == a) {
     i = n + 1;
     a = 0;
     int fin2 = 2, a1 = 1, a2 = 0, a3, x1, x2;
     if (n == 1) {
     fin2 = 0;
     cj2.setText("2 es el par mas cercano de fibonacci para" +" "+ n+"y "+n+"es triangular");
     }
     for (int j = 0; j < fin2; j++) {
     fin2++;
     a3 = a1 + a2;
     if (a3 % 2 == 0) {
     if (a3 == n) {
     cj2.setText(n+" "+"es un numero de fibonacci y es el mas cercano a"+" "+n+"y "+n+"es triangular");
     fin2 = j;
     }
     if (a3 < n) {
     proximo1 = a3;
     }
     if (a3 > n) {
     proximo2 = a3;
     j = fin2;
     }
     }
     a2 = a1;
     a1 = a3;
     }
     x1 = n - proximo1;
     x2 = proximo2 - n;
     if (n != 1) {
     if (x1 < x2) {
     cj2.setText(proximo1+" "+"es el fibonacci mas proximo a: "+" "+n+" "+"y "+n+" "+"es triangular");
     }
     if (x1 > x2) {
     cj2.setText(proximo2+" "+"es el par mas cercano de finobacci para"+" "+n+ " y " +n+ " es triangular");
     }
     if (x1 == x2) {
     cj2.setText(proximo1+" "+"y" +" "+proximo2+" "+"son pares de fibonacci"+","+ " y "+" "+n+"  es triangular");
     }
     }
     }
     }
     if (a != 0) {
     if (n % 2 == 0) {
     int acu4 = 0, fin3 = 2;
     for (int k = 1; k < fin3; k++) {
     fin3++;
     acu4 = acu4 + k;
     if (acu4 % 2 != 0) {
     if (acu4 == n) {
     cj2.setText(n+" "+"es el fibonacci mas proximo a "+" "+n);
     fin3 = k;
     }
     if (acu4 < n) {
     proximo3 = acu4;
     }
     if (acu4 > n) {
     proximo4 = acu4;
     k = fin3;
     }
     }
     }
     x = n - proximo3;
     y = proximo4 - n;
     if (x < y) {
     cj2.setText(proximo3+" "+"es impar y es el triangular mas cercano a:"+n+" y "+n+" no es triangular, es par");
     }
     if (x > y) {
     cj2.setText(proximo4+" "+"es triangular y es el impar mas cercano a"+" "+n+ " y "+n+ " es par");
     }
     if (x == y) {
     cj2.setText(proximo3+" "+"y" +" "+proximo4+" "+"son los impares mas cercanos a los triangulares y el numero: "+n+" "+"no es triangular, es par");
     }
     }
     if (n % 2 != 0) {
     int cont = 0;
     for (int l = 1; l <= n; l++) {
     if (n % l == 0) {
     cont = cont + 1;
     }
     }
     if (cont == 2) {
     cj2.setText(n +" "+"es primo "+"y "+"no es triangular");
     }else{for (int r=1; r<n; r++){
     int cont2=0;
     for(int p=1;p<=r;p++){
     if(r%p==0){
     cont2=cont2+1;
     }
     }
     if(cont2==2){
     primoi=r;
     }
     }
     int finprimo=n+2;
     for (int d=n+1; d<finprimo; d++){
     finprimo++;
     int cont2=0;
     for(int g=1;g<=d;g++){
     if(d%g==0){
     cont2=cont2+1;
     }
     }
     if(cont2==2){
     primod=d;
     finprimo=d;
     }
     }
     int dif1, dif2;
     dif1=n-primoi;
     dif2=primod-n;
     if(dif1<dif2) {
     e1=String.valueOf(primoi +" "+"es primo y esta mas cerca a"+" "+n+ " y el numero "+n+"  no es triangular y aunque es impar no es primo");
     cj2.setText(e1);
     }else{
     if(dif1>dif2){
     e1=String.valueOf(primod+" "+"es primo y esta mas  cerca a"+" "+n+ " y el numero "+n+"  no es triangular y aunque es impar no es primo");
     cj2.setText(e1);
     }else{
     e1=String.valueOf(primoi+" "+"y"+" "+primod)+" "+"son los primos mas cercanos a"+" "+n+" "+"y el numero "+n+" "+"no es triangular y aunque es impar no es primo";
     cj2.setText(e1);
                }
            }
            }
            }
        }

    }//GEN-LAST:event_b1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sugerido1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JTextField cj1;
    private javax.swing.JTextField cj2;
    // End of variables declaration//GEN-END:variables

}
