/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class tiendita extends javax.swing.JFrame {
     DefaultTableModel modelo;
     int id;
    public tiendita() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Producto");
        modelo.addColumn("Stock");
        this.tp1.setModel(modelo);
        Autorizado.setVisible(false);
        PS1.setVisible(true);
        T3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Autorizado = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tproducto = new javax.swing.JTextField();
        tstock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        interfaztienda = new javax.swing.JPanel();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        L4 = new javax.swing.JLabel();
        CB = new javax.swing.JCheckBox();
        b1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        PS1 = new javax.swing.JPasswordField();
        bi = new javax.swing.JButton();

        tp1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Producto", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tp1);

        jButton1.setText("Agregar producto y stock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar fila");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido!, que desea hacer?");

        tproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tproductoActionPerformed(evt);
            }
        });
        tproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tproductoKeyTyped(evt);
            }
        });

        tstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tstockKeyTyped(evt);
            }
        });

        jLabel3.setText("PRODUCTO");
        jLabel3.setToolTipText("");

        jLabel4.setText("STOCK");

        jButton3.setText("Eliminar fila especifica");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
        });

        jMenu1.setText("Atras");
        jMenuBar1.add(jMenu1);

        Autorizado.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout AutorizadoLayout = new javax.swing.GroupLayout(Autorizado.getContentPane());
        Autorizado.getContentPane().setLayout(AutorizadoLayout);
        AutorizadoLayout.setHorizontalGroup(
            AutorizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutorizadoLayout.createSequentialGroup()
                .addGroup(AutorizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutorizadoLayout.createSequentialGroup()
                        .addGroup(AutorizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AutorizadoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AutorizadoLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(AutorizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 27, Short.MAX_VALUE)))
                        .addGap(28, 28, 28))
                    .addGroup(AutorizadoLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(AutorizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(AutorizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tproducto)
                            .addComponent(tstock, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AutorizadoLayout.setVerticalGroup(
            AutorizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(AutorizadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AutorizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AutorizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tstock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AutorizadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        interfaztienda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tienda(1).png"))); // NOI18N
        L1.setText("jLabel4");
        interfaztienda.add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 11, 67, -1));

        L2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L2.setText("TIENDA LOS ROSALES");
        interfaztienda.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 29, -1, -1));

        L3.setText("Usuario");
        interfaztienda.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 93, 99, 23));

        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        interfaztienda.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, -1));

        L4.setText("Contraseña");
        interfaztienda.add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 134, 104, 21));

        CB.setText("Mostrar Contraseña");
        CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBActionPerformed(evt);
            }
        });
        interfaztienda.add(CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        b1.setText("Ingresar");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        interfaztienda.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 146, 37));

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        interfaztienda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 157, 121, -1));
        interfaztienda.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 20));

        PS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS1ActionPerformed(evt);
            }
        });
        interfaztienda.add(PS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 20));

        bi.setText("Ingreso de invitado");
        bi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biActionPerformed(evt);
            }
        });
        interfaztienda.add(bi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(interfaztienda, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(interfaztienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(autenticacion()){
            Autorizado.setVisible(true);
            Autorizado.setBounds(20,20,1000,800);
            interfaztienda.doLayout();
        }
        else{
        JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña no valida");
        }

    }//GEN-LAST:event_b1ActionPerformed
        public boolean autenticacion(){
        String usuario = T1.getText();
        char passArray[] = PS1.getPassword();
        
        for (int i = 0; i < passArray.length; i++){
            char c = passArray[i];if (!Character.isLetterOrDigit(c)) 
            return false;
        }
        String pass = new String(passArray);
        
            return usuario.equals("Fernando")&& pass.equals("claveprivada");
       
            
        /*boolean valido = false;
        for(Trabajador persona:trabajadores){
            valido = user.equals(persona.nombre) && pass.equals(persona.password);
            break;
        }
        return valido;*/
                }
    private void CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBActionPerformed
       if(CB.isSelected()){
       PS1.setVisible(false);
       T3.setVisible(true);
       T3.setText(String.valueOf(PS1.getPassword()));
       }
       else{
       PS1.setVisible(true);
       T3.setVisible(false);
       }
    }//GEN-LAST:event_CBActionPerformed

    private void PS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PS1ActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked
     
    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        id += 1;
        String[] datos = new String[3];
       datos[0] = String.valueOf(id);
       datos[1] = tproducto.getText();
       datos[2] = String.valueOf(tstock.getText());
       modelo.addRow(datos);
       tproducto.setText("");
       tstock.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int tamano = tp1.getRowCount();
      if(tamano > 0){
      modelo.removeRow(tamano-1);
      id -= 1;   
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void biActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biActionPerformed
            Autorizado.setVisible(true);
            Autorizado.setBounds(20,20,400,400);
            interfaztienda.doLayout();
    }//GEN-LAST:event_biActionPerformed

    private void tproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tproductoActionPerformed

    }//GEN-LAST:event_tproductoActionPerformed

    private void tstockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tstockKeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9'){
        evt.consume();
        }
    }//GEN-LAST:event_tstockKeyTyped

    private void tproductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tproductoKeyTyped
      char d = evt.getKeyChar();
      if((d < 'A' || d > 'Z')&&(d < 'a' || d > 'z')){
        evt.consume();
        }
    }//GEN-LAST:event_tproductoKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int fila = tp1.getSelectedRow();
        int cf = tp1.getRowCount();
        if(fila >= 0){
        modelo.removeRow(fila);
        for(int i = fila; i <= cf;i++){
            id =  i+1;
            modelo.setValueAt(String.valueOf(id),i,0);
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiendita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiendita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiendita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiendita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiendita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Autorizado;
    private javax.swing.JCheckBox CB;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JPasswordField PS1;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T3;
    private javax.swing.JButton b1;
    private javax.swing.JButton bi;
    private javax.swing.JPanel interfaztienda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tp1;
    private javax.swing.JTextField tproducto;
    private javax.swing.JTextField tstock;
    // End of variables declaration//GEN-END:variables
}
